import React from 'react';
export const mlDetails = () => <div>ml distinct</div>;
export const ml_detail_0 = (p:any)=> <div>ml 0 defect detection</div>;
export const ml_detail_1 = (p:any)=> <div>ml 1 severity</div>;
export const ml_detail_2 = (p:any)=> <div>ml 2 model</div>;
export const ml_detail_3 = (p:any)=> <div>ml 3 training</div>;
export const ml_detail_4 = (p:any)=> <div>ml 4 defect detection</div>;
export const ml_detail_5 = (p:any)=> <div>ml 5 severity</div>;
export const ml_detail_6 = (p:any)=> <div>ml 6 model</div>;
export const ml_detail_7 = (p:any)=> <div>ml 7 training</div>;
export const ml_detail_8 = (p:any)=> <div>ml 8 defect detection</div>;
export const ml_detail_9 = (p:any)=> <div>ml 9 severity</div>;
export const ml_detail_10 = (p:any)=> <div>ml 10 model</div>;
export const ml_detail_11 = (p:any)=> <div>ml 11 training</div>;
export const ml_detail_12 = (p:any)=> <div>ml 12 defect detection</div>;
export const ml_detail_13 = (p:any)=> <div>ml 13 severity</div>;
export const ml_detail_14 = (p:any)=> <div>ml 14 model</div>;
export const ml_detail_15 = (p:any)=> <div>ml 15 training</div>;
export const ml_detail_16 = (p:any)=> <div>ml 16 defect detection</div>;
export const ml_detail_17 = (p:any)=> <div>ml 17 severity</div>;
export const ml_detail_18 = (p:any)=> <div>ml 18 model</div>;
export const ml_detail_19 = (p:any)=> <div>ml 19 training</div>;