import React from 'react';
export const reportingDetails = () => <div>reporting distinct</div>;
export const reporting_detail_0 = (p:any)=> <div>reporting 0 inspection report</div>;
export const reporting_detail_1 = (p:any)=> <div>reporting 1 asset history</div>;
export const reporting_detail_2 = (p:any)=> <div>reporting 2 PDF</div>;
export const reporting_detail_3 = (p:any)=> <div>reporting 3 csv</div>;
export const reporting_detail_4 = (p:any)=> <div>reporting 4 inspection report</div>;
export const reporting_detail_5 = (p:any)=> <div>reporting 5 asset history</div>;
export const reporting_detail_6 = (p:any)=> <div>reporting 6 PDF</div>;
export const reporting_detail_7 = (p:any)=> <div>reporting 7 csv</div>;
export const reporting_detail_8 = (p:any)=> <div>reporting 8 inspection report</div>;
export const reporting_detail_9 = (p:any)=> <div>reporting 9 asset history</div>;
export const reporting_detail_10 = (p:any)=> <div>reporting 10 PDF</div>;
export const reporting_detail_11 = (p:any)=> <div>reporting 11 csv</div>;
export const reporting_detail_12 = (p:any)=> <div>reporting 12 inspection report</div>;
export const reporting_detail_13 = (p:any)=> <div>reporting 13 asset history</div>;
export const reporting_detail_14 = (p:any)=> <div>reporting 14 PDF</div>;
export const reporting_detail_15 = (p:any)=> <div>reporting 15 csv</div>;
export const reporting_detail_16 = (p:any)=> <div>reporting 16 inspection report</div>;
export const reporting_detail_17 = (p:any)=> <div>reporting 17 asset history</div>;
export const reporting_detail_18 = (p:any)=> <div>reporting 18 PDF</div>;
export const reporting_detail_19 = (p:any)=> <div>reporting 19 csv</div>;