import React from 'react';
export const schedulingDetails = () => <div>scheduling distinct</div>;
export const scheduling_detail_0 = (p:any)=> <div>scheduling 0 follow-up</div>;
export const scheduling_detail_1 = (p:any)=> <div>scheduling 1 regulatory intervals</div>;
export const scheduling_detail_2 = (p:any)=> <div>scheduling 2 priority</div>;
export const scheduling_detail_3 = (p:any)=> <div>scheduling 3 calendar</div>;
export const scheduling_detail_4 = (p:any)=> <div>scheduling 4 follow-up</div>;
export const scheduling_detail_5 = (p:any)=> <div>scheduling 5 regulatory intervals</div>;
export const scheduling_detail_6 = (p:any)=> <div>scheduling 6 priority</div>;
export const scheduling_detail_7 = (p:any)=> <div>scheduling 7 calendar</div>;
export const scheduling_detail_8 = (p:any)=> <div>scheduling 8 follow-up</div>;
export const scheduling_detail_9 = (p:any)=> <div>scheduling 9 regulatory intervals</div>;
export const scheduling_detail_10 = (p:any)=> <div>scheduling 10 priority</div>;
export const scheduling_detail_11 = (p:any)=> <div>scheduling 11 calendar</div>;
export const scheduling_detail_12 = (p:any)=> <div>scheduling 12 follow-up</div>;
export const scheduling_detail_13 = (p:any)=> <div>scheduling 13 regulatory intervals</div>;
export const scheduling_detail_14 = (p:any)=> <div>scheduling 14 priority</div>;
export const scheduling_detail_15 = (p:any)=> <div>scheduling 15 calendar</div>;
export const scheduling_detail_16 = (p:any)=> <div>scheduling 16 follow-up</div>;
export const scheduling_detail_17 = (p:any)=> <div>scheduling 17 regulatory intervals</div>;
export const scheduling_detail_18 = (p:any)=> <div>scheduling 18 priority</div>;
export const scheduling_detail_19 = (p:any)=> <div>scheduling 19 calendar</div>;