import React from 'react';
export const inspectionsDetails = () => <div>inspections distinct</div>;
export const inspections_detail_0 = (p:any)=> <div>inspections 0 field</div>;
export const inspections_detail_1 = (p:any)=> <div>inspections 1 photos</div>;
export const inspections_detail_2 = (p:any)=> <div>inspections 2 sensor readings</div>;
export const inspections_detail_3 = (p:any)=> <div>inspections 3 mobile</div>;
export const inspections_detail_4 = (p:any)=> <div>inspections 4 field</div>;
export const inspections_detail_5 = (p:any)=> <div>inspections 5 photos</div>;
export const inspections_detail_6 = (p:any)=> <div>inspections 6 sensor readings</div>;
export const inspections_detail_7 = (p:any)=> <div>inspections 7 mobile</div>;
export const inspections_detail_8 = (p:any)=> <div>inspections 8 field</div>;
export const inspections_detail_9 = (p:any)=> <div>inspections 9 photos</div>;
export const inspections_detail_10 = (p:any)=> <div>inspections 10 sensor readings</div>;
export const inspections_detail_11 = (p:any)=> <div>inspections 11 mobile</div>;
export const inspections_detail_12 = (p:any)=> <div>inspections 12 field</div>;
export const inspections_detail_13 = (p:any)=> <div>inspections 13 photos</div>;
export const inspections_detail_14 = (p:any)=> <div>inspections 14 sensor readings</div>;
export const inspections_detail_15 = (p:any)=> <div>inspections 15 mobile</div>;
export const inspections_detail_16 = (p:any)=> <div>inspections 16 field</div>;
export const inspections_detail_17 = (p:any)=> <div>inspections 17 photos</div>;
export const inspections_detail_18 = (p:any)=> <div>inspections 18 sensor readings</div>;
export const inspections_detail_19 = (p:any)=> <div>inspections 19 mobile</div>;